project: 
  type: website
  
website: 
  page-navigation: true
  title: "Openscapes Champions Series"

  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "@Copyright ? Ké cé cé ?❤️"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/logoherinew.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/hunykorn
        text: "Lucas GitHub"
      - icon: twitter
        href: https://twitter.com/openscapes
        text: "Openscapes Twitter"        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: "index.qmd"
        text: Accueil
      - section: Cours
        contents:        
         - href: "core-lessons/tableauNumpy.qmd"
           text: Tableau Numpy
         - href: core-lessons/constanteNumpy.qmd
           text: Constante Fournie
         - href: "core-lessons/operationTableau.qmd"
           text: Opération sur les Tableaux
         - href: "core-lessons/produitSomme.qmd"
           text: Produit et Somme
         - href: "core-lessons/fonctionUtiles.qmd"
           text: Fonctions Utiles
         - href: "core-lessons/fonctionMath.qmd"
           text: Fonctions Mathématiques
         - href: "core-lessons/fonctionRecherche.qmd"
           text: Fonctions de Recherches
         - href: "core-lessons/assamblageTableau.qmd"
           text: Assemblage de plusieurs tableaux
      - href: "Exercice.qmd"
        text: Exercice

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true #false pour cacher sidebar



  
